# Exported from Render on 2025-12-21T09:22:34Z
version: "1"
services:
- type: web
  name: backend-govigi
  runtime: node
  repo: https://github.com/Govigi/backend
  branch: production
  plan: free
  envVars:
  - key: TWO_FACTOR_TEMPLATE_NAME
    sync: false
  - key: TWO_FACTOR_SENDER_ID
    sync: false
  - key: TWO_FACTOR_API_KEY
    sync: false
  - key: SCERET_KEY
    sync: false
  - key: PORT
    sync: false
  - key: NODE_ENV
    sync: false
  - key: MONGODB
    sync: false
  - key: GOOGLE_MAPS_API_KEY
    sync: false
  - key: F2S_API_KEY
    sync: false
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: CLOUDINARY_API_SCERET_KEY
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node app.js
  autoDeployTrigger: commit
